import React from "react";
import AnimatedCounter from "../ui/AnimatedCounter";
import GradientText from "../ui/GradientText";

export default function OurStory() {
  // --- Define the styles from your spec ---

  // For the numbers: Inter 700, 48px, gradient text
  const numberStyles = `
    font-bold text-5xl leading-[56px] 
    bg-gradient-to-r from-[#42A5F5] to-[#7E57C2] 
    bg-clip-text text-transparent
  `;

  // For the labels: Inter 400, 16px
  const labelStyles = "font-normal text-base leading-6 text-[#1A1A1A] mt-2";

  return (
    <section className="bg-[#F5F5F7] py-16 md:py-24 lg:mb-20">
      <div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        {/* --- Top Section: Title & Paragraph --- */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-16 items-center">
          {/* Left Column: Title */}
          <div>
            <GradientText
              colors={["#51C4F6", "#4A66CC", "#7A45C5", "#FF8A3D", "#FFC34A"]}
              animationSpeed={5}
              showBorder={false}
              className="ml-0"
            >
              <h1 className="font-bold text-5xl leading-14">Our Story</h1>
            </GradientText>
          </div>

          {/* Right Column: Paragraph */}
          <div>
            <p
              className="font-normal text-lg leading-7 text-[#1A1A1A]"
              style={{ letterSpacing: "0px" }}
            >
              From the beginning, Flexiana was built on a simple idea: don’t
              compromise when the right solution is within reach. Since 2016,
              that belief has guided us. Our passion for good software and
              genuine collaboration has helped us create meaningful results for
              companies around the world.
            </p>
          </div>
        </div>

        {/* --- Bottom Section: Stats Grid --- */}
        {/*
          - Mobile: 2-column grid
          - Desktop: 4-column grid
        */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-y-12 lg:gap-y-0 gap-x-8 mt-16 md:mt-24 text-center">
          {/* Stat 1: Client Retention */}
          <div>
            <AnimatedCounter
              className={numberStyles}
              targetValue={92}
              prefix="+"
              suffix="%"
            />
            <p className={labelStyles}>Client Retention Ratio</p>
          </div>

          {/* Stat 2: Generated */}
          <div>
            <AnimatedCounter
              className={numberStyles}
              targetValue={1.2}
              precision={1}
              prefix="$"
              suffix="B"
            />
            <p className={labelStyles}>Generated by Our Clients</p>
          </div>

          {/* Stat 3: Experience */}
          <div>
            <AnimatedCounter
              className={numberStyles}
              targetValue={12}
              suffix="YRS"
            />
            <p className={labelStyles}>Industry Experience</p>
          </div>

          {/* Stat 4: Team Experts */}
          <div>
            <AnimatedCounter
              className={numberStyles}
              targetValue={45}
              suffix="+"
            />
            <p className={labelStyles}>
              Team Experts from the EU and Latin America
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
