import type { Metadata } from "next";
import { fontHelvetica } from "./fonts";
import "./globals.css";
import SplinePrefetcher from "@/components/SplinePrefetcher";
import SmoothScrolling from "@/components/SmoothScrolling";
import { ToastProvider } from "@/components/providers/ToastProvider";

import { AuthProvider } from "@/components/providers/AuthProvider";

export const metadata: Metadata = {
  title: "Flexiana AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>

      </head>
      <body
        className={`${fontHelvetica.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <AuthProvider>
          <SmoothScrolling />
          {children}
          <SplinePrefetcher />
          <ToastProvider />
        </AuthProvider>
      </body>
    </html>
  );
}
